### ISSUE TITLE
SIGURG (signal "urgent I/O condition") causes a panic

### ISSUE THREAD

**Issue by hiroakis** [winebarrel/ecs-exec-pf#1]
It occasionally happens a panic when I run [demitas-pf](https://github.com/winebarrel/demitas) command.

```
# demitas-pf -p xxxx -h xxxx -r 5432 -l 15432

Start ECS task for port forwarding...
ECS task is running: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Start port forwarding...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10dd8db]

goroutine 8 [running]:
os.(*Process).signal(0x0, 0x1579948, 0x179cce0, 0x0, 0x0)
        /usr/local/Cellar/go/1.16/libexec/src/os/exec_unix.go:63 +0x3b
os.(*Process).Signal(...)
        /usr/local/Cellar/go/1.16/libexec/src/os/exec.go:135
github.com/winebarrel/ecs-exec-pf.runCommand.func1(0xc0002de540, 0xc0000cdb80)
        /Users/sano/work/src/github.com/winebarrel/ecs-exec-pf/session_manager.go:50 +0x66
created by github.com/winebarrel/ecs-exec-pf.runCommand
        /Users/sano/work/src/github.com/winebarrel/ecs-exec-pf/session_manager.go:47 +0x191
```

After some debugging, I found it receives SIGURG (urgent I/O condition) and also found https://github.com/golang/go/issues/37942. According to the issue it cause Go >= 1.14.

**Comment by hiroakis** [comment]
@winebarrel I'm sending a PR (https://github.com/winebarrel/ecs-exec-pf/pull/2). Could you check the issue and review that.
